server:
  port: 8585

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: admin_api
    password: U7AC|bd~>Pr<l49g74*&u#w7~
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    schemas: public

springdoc:
  swagger-ui:
    default-models-expand-depth: -1
    path: /api-docs-ui.html
  api-docs:
    path: /api-docs


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
          expiration: 604800000

scoring:
  base-url: https://scoringtest.credable.io
  scoring-url: /api/v1/scoring/initiateQueryScore/
  query-score: /api/v1/scoring/queryScore/
  registration-url: https://scoringtest.credable.io/api/v1/client/createClient
  callback-url: https://28a4-41-80-117-125.ngrok-free.app/api/v1/transactions/{customerNumber}
  client-name: "LMS Service"
  callback-username: scoring-client
  callback-password: scoring123

credable:
  username: "admin"
  password: "pwd123"
