name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test # Skip tests

      - name: Copy JAR file
        run: |
          cp build/libs/lms-api-0.0.1-SNAPSHOT.jar ${{ github.workspace }}/lms-api-0.0.1-SNAPSHOT.jar

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lms-api-jar
          path: ${{ github.workspace }}/lms-api-0.0.1-SNAPSHOT.jar

      - name: Copy JAR to Contabo VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USERNAME }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          port: ${{ secrets.CONTABO_PORT }}
          source: "lms-api-0.0.1-SNAPSHOT.jar"
          target: "/home/devops/lms/lms-api"

      - name: Execute script on Contabo VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USERNAME }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          port: ${{ secrets.CONTABO_PORT }}
          script: |
            nohup bash /home/devops/lms/lms-api/lms.sh > app.log 2>&1 &
